#*******************************MASTER KEYS*************************************
CREATED = 'created'
MODIFIED = 'modified'
MASTER_EXCLUDE = [CREATED, MODIFIED]
NAME = 'name'
SUCCESS = 'success'
MESSAGE = 'message'
STATUS = 'status'
ERROR = 'error'
INSTANCE = 'instance'
BOTH = 'both'
ID = 'id'
DATA_ID = 'data_id'
#*************API METHOD******************
DELETE = 'DELETE'
POST = 'POST'
GET = 'GET'
PATCH = 'PATCH'
#*****************************************
#*******************************************************************************
#*********************************AUTH KEYS*************************************
EMAIL = 'email'
PHONE = 'phone'
PASSWORD = 'password'
IAT = 'iat'
EXP = 'exp'
HS256 = 'HS256'
REFRESH_TOKEN = 'rtoken'
TOKEN = 'token'
HTTP_TOKEN = 'HTTP_TOKEN'
HTTP_REFRESH_TOKEN = 'HTTP_RTOKEN'
#*******************************************************************************
#*********************************USER KEYS*************************************
USER = 'user'
USER_ID = 'user_id'
USER_NAME = 'username'
#*******************************************************************************
#*********************************FORM KEYS*************************************
FORM_NAME = 'form_name'
FIELD_NAME = 'field_name'
FIELD_KEY = 'field_key'
FIELD_TYPE = 'type'
FIELD_OPTIONS = 'options'
FIELD_MANDATORY = 'mandatory'
TEXT_TYPE = 'text'
SINGLE_SELECT_TYPE = 'singleSelect'
NUMBER_TYPE = 'number'
DATE_TYPE = 'date'
FIELD_TRUE = 'true'
FIELD_FALSE = 'false'
FIELD_CHOICES = 'choices'
NULL = 'null'
BLANK = 'blank'
MAX_LENGTH = 'max_length'
DB_COLUMN = 'db_column'
VERBOSE_NAME = 'verbose_name'
FORM_DETAIL = 'form_detail'
FORM_DATA = 'form_data'
FORM_DATA_LIST = 'form_data_list'
FORM_FIELD_DETAIL = 'form_field_detail'
FORM_LIST = 'form_list'
FORM_ID = 'form_id'
USER_FORM = 'user_form'
CHARFIELD = 'CharField'
INTEGERFIELD = 'IntegerField'
DATEFIELD = 'DateField'
IS_FORM_CREATED = 'is_form_created'
FIELD_TYPE_OBJECT = {CHARFIELD:TEXT_TYPE, INTEGERFIELD:NUMBER_TYPE,DATEFIELD:DATE_TYPE,SINGLE_SELECT_TYPE:SINGLE_SELECT_TYPE}
FILTER_FIELD = 'filter_field'
DISPLAY_FIELD = 'display_field'
#*******************************************************************************